-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHdfUb7AyjLfKIMbS
NjUlmaSe5AOZQ+7tkiFwiRTwcH2gCgYIKoZIzj0DAQehRANCAARGMuX8BPgKoltx
ZMlyyyDUqrQPzYJVVGN14vZoyil+JsYQSeh1YamyZuOgZIG+/37qL4qDS0mJEQP8
+Kp5tzhK
-----END PRIVATE KEY-----